# Generated by Django 5.2.7 on 2025-11-05 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('native', 'Native PDF'), ('scanned', 'Scanned PDF')], default='native', max_length=20),
        ),
        migrations.AddField(
            model_name='document',
            name='ocr_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='ocr_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='ocr_text',
            field=models.TextField(blank=True, help_text='Extracted text from OCR', null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='processed_file',
            field=models.FileField(blank=True, help_text='PDF with OCR text layer', null=True, upload_to='documents/processed/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='document',
            name='processing_state',
            field=models.CharField(choices=[('pending', 'Pending'), ('ocr_queued', 'OCR Queued'), ('ocr_processing', 'OCR Processing'), ('ocr_completed', 'OCR Completed'), ('ocr_failed', 'OCR Failed'), ('rag_processing', 'RAG Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
