"""
Django settings for DocSeek project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-q+9k%$(khj8ua9p_l8$souikf(9-#f+n-g9i=eu68i0c_+k5)d'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'users',
    'doc_manager',
    'django_celery_results',
    'debug_toolbar',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'database' /'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Impostazioni Statici Globali
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Redirect URLs for login and logout
LOGIN_REDIRECT_URL = '/'  # Redirect to home after login
LOGOUT_REDIRECT_URL = '/'  # Redirect to login after logout

# Configuration for User-Uploaded Files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Impostazioni che chiude la sessione alla chiusura del browser
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

# Celery Configuration Options
CELERY_BROKER_URL = 'redis://127.0.0.1:6379/0' # Deve puntare al Redis di Docker
CELERY_RESULT_BACKEND = 'django-db'

# ==================== GPU OCR SERVER CONFIGURATION ====================

# URL del server GPU per OCR
# Opzione A: Connessione diretta (se firewall lo permette)
#GPU_SERVER_URL = 'http://solaris.micc.unifi.it:8000'

# Opzione B: SSH Tunnel (se firewall blocca)
# Ricorda di avviare il tunnel prima:
# ssh -N -L 8000:localhost:8000 albanhaka@solaris.micc.unifi.it
#GPU_SERVER_URL = 'http://localhost:8000'




INTERNAL_IPS = [
    '127.0.0.1'
]

# ==================== LAMBDA.AI GPU CONFIGURATION ====================

# URL del server GPU Lambda.ai per OCR
# IMPORTANTE: Cambierai questo dopo aver configurato Lambda.ai
#GPU_SERVER_URL = 'http://163.192.12.203:8000'

# Opzione B: Tunnel SSH (consigliato se l'IP cambia)
# Esegui sul tuo PC/server Django:
# ssh -N -L 8000:localhost:8000 ubuntu@163.192.12.203
GPU_SERVER_URL = 'http://localhost:8000'


# Timeout per richieste OCR (in secondi)
OCR_REQUEST_TIMEOUT = 300  # 5 minuti

# ==================== CELERY TASK ROUTES ====================

# Separazione delle code Celery
CELERY_TASK_ROUTES = {
    # Task OCR (comunicazione con Lambda.ai)
    'doc_manager.tasks.process_scanned_document': {'queue': 'ocr'},
    'doc_manager.tasks.check_ocr_status': {'queue': 'ocr'},
    
    # Task RAG (elaborazione locale)
    'doc_manager.tasks.index_document_rag': {'queue': 'default'},
}

# Task limits
CELERY_TASK_TIME_LIMIT = 3600  # 1 ora max
CELERY_TASK_SOFT_TIME_LIMIT = 3000  # 50 minuti